// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
// Version: 2019.2
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="multihat,hls_ip_2019_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=1,HLS_INPUT_PART=xc7a35t-cpg236-1,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=pipeline,HLS_SYN_CLOCK=7.610500,HLS_SYN_LAT=1,HLS_SYN_TPT=1,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=263,HLS_SYN_LUT=448,HLS_VERSION=2019_2}" *)

module multihat (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        seed_V,
        reset,
        out_V,
        out_V_ap_vld
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [129:0] seed_V;
input   reset;
output  [15:0] out_V;
output   out_V_ap_vld;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg out_V_ap_vld;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_idle_pp0;
reg    ap_block_state1_pp0_stage0_iter0;
wire    ap_block_state2_pp0_stage0_iter1;
reg    ap_block_pp0_stage0_11001;
reg   [15:0] z1_V;
reg   [15:0] z_V;
reg   [15:0] z1_V_5;
reg   [15:0] z_V_5;
reg   [15:0] z1_V_4;
reg   [15:0] z_V_4;
reg   [15:0] z1_V_3;
reg   [15:0] z_V_3;
reg    ap_block_pp0_stage0_subdone;
reg    grp_LFSR_fu_199_ap_start;
wire    grp_LFSR_fu_199_ap_done;
wire    grp_LFSR_fu_199_ap_idle;
wire    grp_LFSR_fu_199_ap_ready;
wire   [127:0] grp_LFSR_fu_199_ap_return;
wire    ap_block_pp0_stage0;
wire   [15:0] select_ln301_2_fu_483_p3;
wire   [15:0] select_ln301_3_fu_529_p3;
wire   [15:0] select_ln301_6_fu_823_p3;
wire   [15:0] select_ln301_7_fu_875_p3;
wire   [15:0] select_ln301_10_fu_1169_p3;
wire   [15:0] select_ln301_11_fu_1221_p3;
wire   [15:0] select_ln301_14_fu_1515_p3;
wire   [15:0] select_ln301_15_fu_1567_p3;
reg    ap_block_pp0_stage0_01001;
wire   [0:0] tmp_1_fu_225_p3;
wire   [0:0] tmp_fu_217_p3;
wire   [0:0] tmp_2_fu_233_p3;
wire   [0:0] xor_ln37_1_fu_247_p2;
wire   [0:0] xor_ln37_fu_241_p2;
wire   [0:0] xor_ln37_2_fu_253_p2;
wire   [0:0] tmp_3_fu_265_p3;
wire   [0:0] tmp_4_fu_273_p3;
wire   [0:0] xor_ln38_1_fu_287_p2;
wire   [1:0] p_Result_1_fu_303_p4;
wire   [12:0] trunc_ln647_fu_299_p1;
wire   [1:0] p_Result_3_fu_323_p4;
wire   [0:0] c_V_fu_259_p2;
wire   [15:0] p_Result_4_fu_333_p4;
wire   [0:0] xor_ln38_fu_281_p2;
wire   [0:0] and_ln301_fu_351_p2;
wire   [0:0] xor_ln38_2_fu_293_p2;
wire   [0:0] and_ln301_1_fu_357_p2;
wire   [15:0] p_Result_2_fu_313_p4;
wire   [15:0] select_ln301_fu_343_p3;
wire   [0:0] tmp_5_fu_371_p3;
wire   [0:0] tmp_7_fu_387_p3;
wire   [0:0] or_ln53_fu_403_p2;
wire   [0:0] tmp_6_fu_379_p3;
wire   [0:0] or_ln53_1_fu_409_p2;
wire   [0:0] tmp_10_fu_395_p3;
wire   [0:0] tmp_11_fu_421_p3;
wire   [0:0] tmp_13_fu_437_p3;
wire   [0:0] and_ln301_3_fu_445_p2;
wire   [0:0] tmp_12_fu_429_p3;
wire   [0:0] tmp_14_fu_465_p3;
wire   [13:0] trunc_ln647_1_fu_461_p1;
wire   [0:0] b_V_fu_451_p2;
wire   [15:0] p_Result_s_fu_473_p4;
wire   [0:0] tmp_15_fu_501_p3;
wire   [0:0] p_Result_56_fu_509_p3;
wire   [12:0] trunc_ln647_2_fu_497_p1;
wire   [0:0] a_V_fu_415_p2;
wire   [15:0] p_Result_9_fu_517_p5;
wire   [15:0] p_Result_10_fu_209_p1;
wire   [0:0] tmp_18_fu_565_p3;
wire   [0:0] tmp_17_fu_557_p3;
wire   [0:0] tmp_19_fu_573_p3;
wire   [0:0] xor_ln85_1_fu_587_p2;
wire   [0:0] xor_ln85_fu_581_p2;
wire   [0:0] xor_ln85_2_fu_593_p2;
wire   [0:0] tmp_20_fu_605_p3;
wire   [0:0] tmp_21_fu_613_p3;
wire   [0:0] xor_ln86_1_fu_627_p2;
wire   [1:0] p_Result_s_6_fu_643_p4;
wire   [12:0] trunc_ln647_3_fu_639_p1;
wire   [1:0] p_Result_6_fu_663_p4;
wire   [0:0] c_V_1_fu_599_p2;
wire   [15:0] p_Result_7_fu_673_p4;
wire   [0:0] xor_ln86_fu_621_p2;
wire   [0:0] and_ln301_6_fu_691_p2;
wire   [0:0] xor_ln86_2_fu_633_p2;
wire   [0:0] and_ln301_7_fu_697_p2;
wire   [15:0] p_Result_5_fu_653_p4;
wire   [15:0] select_ln301_4_fu_683_p3;
wire   [0:0] tmp_22_fu_711_p3;
wire   [0:0] tmp_24_fu_727_p3;
wire   [0:0] or_ln101_fu_743_p2;
wire   [0:0] tmp_23_fu_719_p3;
wire   [0:0] or_ln101_1_fu_749_p2;
wire   [0:0] tmp_25_fu_735_p3;
wire   [0:0] tmp_26_fu_761_p3;
wire   [0:0] tmp_28_fu_777_p3;
wire   [0:0] and_ln301_9_fu_785_p2;
wire   [0:0] tmp_27_fu_769_p3;
wire   [0:0] tmp_29_fu_805_p3;
wire   [13:0] trunc_ln647_4_fu_801_p1;
wire   [0:0] b_V_1_fu_791_p2;
wire   [15:0] p_Result_8_fu_813_p4;
wire   [0:0] tmp_30_fu_847_p3;
wire   [0:0] p_Result_57_fu_855_p3;
wire   [12:0] p_Result_11_fu_837_p4;
wire   [0:0] a_V_1_fu_755_p2;
wire   [15:0] p_Result_12_fu_863_p5;
wire   [15:0] p_Result_26_fu_543_p4;
wire   [0:0] tmp_33_fu_911_p3;
wire   [0:0] tmp_32_fu_903_p3;
wire   [0:0] tmp_34_fu_919_p3;
wire   [0:0] xor_ln133_1_fu_933_p2;
wire   [0:0] xor_ln133_fu_927_p2;
wire   [0:0] xor_ln133_2_fu_939_p2;
wire   [0:0] tmp_35_fu_951_p3;
wire   [0:0] tmp_36_fu_959_p3;
wire   [0:0] xor_ln134_1_fu_973_p2;
wire   [1:0] p_Result_13_fu_989_p4;
wire   [12:0] trunc_ln647_5_fu_985_p1;
wire   [1:0] p_Result_15_fu_1009_p4;
wire   [0:0] c_V_2_fu_945_p2;
wire   [15:0] p_Result_16_fu_1019_p4;
wire   [0:0] xor_ln134_fu_967_p2;
wire   [0:0] and_ln301_12_fu_1037_p2;
wire   [0:0] xor_ln134_2_fu_979_p2;
wire   [0:0] and_ln301_13_fu_1043_p2;
wire   [15:0] p_Result_14_fu_999_p4;
wire   [15:0] select_ln301_8_fu_1029_p3;
wire   [0:0] tmp_37_fu_1057_p3;
wire   [0:0] tmp_39_fu_1073_p3;
wire   [0:0] or_ln149_fu_1089_p2;
wire   [0:0] tmp_38_fu_1065_p3;
wire   [0:0] or_ln149_1_fu_1095_p2;
wire   [0:0] tmp_40_fu_1081_p3;
wire   [0:0] tmp_41_fu_1107_p3;
wire   [0:0] tmp_43_fu_1123_p3;
wire   [0:0] and_ln301_15_fu_1131_p2;
wire   [0:0] tmp_42_fu_1115_p3;
wire   [0:0] tmp_44_fu_1151_p3;
wire   [13:0] trunc_ln647_6_fu_1147_p1;
wire   [0:0] b_V_2_fu_1137_p2;
wire   [15:0] p_Result_17_fu_1159_p4;
wire   [0:0] tmp_45_fu_1193_p3;
wire   [0:0] p_Result_58_fu_1201_p3;
wire   [12:0] p_Result_18_fu_1183_p4;
wire   [0:0] a_V_2_fu_1101_p2;
wire   [15:0] p_Result_19_fu_1209_p5;
wire   [15:0] p_Result_41_fu_889_p4;
wire   [0:0] tmp_48_fu_1257_p3;
wire   [0:0] tmp_47_fu_1249_p3;
wire   [0:0] tmp_49_fu_1265_p3;
wire   [0:0] xor_ln181_1_fu_1279_p2;
wire   [0:0] xor_ln181_fu_1273_p2;
wire   [0:0] xor_ln181_2_fu_1285_p2;
wire   [0:0] tmp_50_fu_1297_p3;
wire   [0:0] tmp_51_fu_1305_p3;
wire   [0:0] xor_ln182_1_fu_1319_p2;
wire   [1:0] p_Result_20_fu_1335_p4;
wire   [12:0] trunc_ln647_7_fu_1331_p1;
wire   [1:0] p_Result_22_fu_1355_p4;
wire   [0:0] c_V_3_fu_1291_p2;
wire   [15:0] p_Result_23_fu_1365_p4;
wire   [0:0] xor_ln182_fu_1313_p2;
wire   [0:0] and_ln301_18_fu_1383_p2;
wire   [0:0] xor_ln182_2_fu_1325_p2;
wire   [0:0] and_ln301_19_fu_1389_p2;
wire   [15:0] p_Result_21_fu_1345_p4;
wire   [15:0] select_ln301_12_fu_1375_p3;
wire   [0:0] tmp_52_fu_1403_p3;
wire   [0:0] tmp_54_fu_1419_p3;
wire   [0:0] or_ln197_fu_1435_p2;
wire   [0:0] tmp_53_fu_1411_p3;
wire   [0:0] or_ln197_1_fu_1441_p2;
wire   [0:0] tmp_55_fu_1427_p3;
wire   [0:0] tmp_56_fu_1453_p3;
wire   [0:0] tmp_58_fu_1469_p3;
wire   [0:0] and_ln301_21_fu_1477_p2;
wire   [0:0] tmp_57_fu_1461_p3;
wire   [0:0] tmp_59_fu_1497_p3;
wire   [13:0] trunc_ln647_8_fu_1493_p1;
wire   [0:0] b_V_3_fu_1483_p2;
wire   [15:0] p_Result_24_fu_1505_p4;
wire   [0:0] tmp_60_fu_1539_p3;
wire   [0:0] p_Result_59_fu_1547_p3;
wire   [12:0] p_Result_25_fu_1529_p4;
wire   [0:0] a_V_3_fu_1447_p2;
wire   [15:0] p_Result_27_fu_1555_p5;
wire   [15:0] p_Result_49_fu_1235_p4;
wire   [15:0] hat_mul_out1_V_fu_363_p3;
wire   [0:0] p_Result_60_fu_1581_p3;
wire   [15:0] hat_mul_out2_V_fu_703_p3;
wire   [0:0] p_Result_62_fu_1597_p3;
wire   [16:0] p_Result_63_fu_1605_p3;
wire   [16:0] p_Result_61_fu_1589_p3;
wire   [15:0] hat_mul_out3_V_fu_1049_p3;
wire   [0:0] p_Result_64_fu_1619_p3;
wire   [15:0] hat_mul_out4_V_fu_1395_p3;
wire   [0:0] p_Result_66_fu_1635_p3;
wire   [16:0] p_Result_67_fu_1643_p3;
wire   [16:0] p_Result_65_fu_1627_p3;
wire   [16:0] s00_V_fu_1613_p2;
wire   [0:0] p_Result_68_fu_1667_p3;
wire   [15:0] p_Result_32_fu_1657_p4;
wire   [16:0] s01_V_fu_1651_p2;
wire   [0:0] p_Result_69_fu_1693_p3;
wire   [15:0] p_Result_33_fu_1683_p4;
wire   [16:0] tmp_9_fu_1701_p3;
wire   [16:0] tmp_8_fu_1675_p3;
wire   [16:0] s10_V_fu_1709_p2;
reg   [0:0] ap_NS_fsm;
reg    ap_idle_pp0_0to0;
reg    ap_reset_idle_pp0;
wire    ap_enable_pp0;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 z1_V = 16'd0;
#0 z_V = 16'd0;
#0 z1_V_5 = 16'd0;
#0 z_V_5 = 16'd0;
#0 z1_V_4 = 16'd0;
#0 z_V_4 = 16'd0;
#0 z1_V_3 = 16'd0;
#0 z_V_3 = 16'd0;
end

LFSR grp_LFSR_fu_199(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_LFSR_fu_199_ap_start),
    .ap_done(grp_LFSR_fu_199_ap_done),
    .ap_idle(grp_LFSR_fu_199_ap_idle),
    .ap_ready(grp_LFSR_fu_199_ap_ready),
    .seed_V(seed_V),
    .ap_return(grp_LFSR_fu_199_ap_return)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        z1_V <= select_ln301_2_fu_483_p3;
        z1_V_3 <= select_ln301_14_fu_1515_p3;
        z1_V_4 <= select_ln301_10_fu_1169_p3;
        z1_V_5 <= select_ln301_6_fu_823_p3;
        z_V <= select_ln301_3_fu_529_p3;
        z_V_3 <= select_ln301_15_fu_1567_p3;
        z_V_4 <= select_ln301_11_fu_1221_p3;
        z_V_5 <= select_ln301_7_fu_875_p3;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter0 == 1'b0)) begin
        ap_idle_pp0_0to0 = 1'b1;
    end else begin
        ap_idle_pp0_0to0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (ap_idle_pp0_0to0 == 1'b1))) begin
        ap_reset_idle_pp0 = 1'b1;
    end else begin
        ap_reset_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b1) & (1'b0 == ap_block_pp0_stage0) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_LFSR_fu_199_ap_start = 1'b1;
    end else begin
        grp_LFSR_fu_199_ap_start = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        out_V_ap_vld = 1'b1;
    end else begin
        out_V_ap_vld = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign a_V_1_fu_755_p2 = (tmp_25_fu_735_p3 & or_ln101_1_fu_749_p2);

assign a_V_2_fu_1101_p2 = (tmp_40_fu_1081_p3 & or_ln149_1_fu_1095_p2);

assign a_V_3_fu_1447_p2 = (tmp_55_fu_1427_p3 & or_ln197_1_fu_1441_p2);

assign a_V_fu_415_p2 = (tmp_10_fu_395_p3 & or_ln53_1_fu_409_p2);

assign and_ln301_12_fu_1037_p2 = (xor_ln134_fu_967_p2 & c_V_2_fu_945_p2);

assign and_ln301_13_fu_1043_p2 = (xor_ln134_2_fu_979_p2 & and_ln301_12_fu_1037_p2);

assign and_ln301_15_fu_1131_p2 = (tmp_43_fu_1123_p3 & tmp_41_fu_1107_p3);

assign and_ln301_18_fu_1383_p2 = (xor_ln182_fu_1313_p2 & c_V_3_fu_1291_p2);

assign and_ln301_19_fu_1389_p2 = (xor_ln182_2_fu_1325_p2 & and_ln301_18_fu_1383_p2);

assign and_ln301_1_fu_357_p2 = (xor_ln38_2_fu_293_p2 & and_ln301_fu_351_p2);

assign and_ln301_21_fu_1477_p2 = (tmp_58_fu_1469_p3 & tmp_56_fu_1453_p3);

assign and_ln301_3_fu_445_p2 = (tmp_13_fu_437_p3 & tmp_11_fu_421_p3);

assign and_ln301_6_fu_691_p2 = (xor_ln86_fu_621_p2 & c_V_1_fu_599_p2);

assign and_ln301_7_fu_697_p2 = (xor_ln86_2_fu_633_p2 & and_ln301_6_fu_691_p2);

assign and_ln301_9_fu_785_p2 = (tmp_28_fu_777_p3 & tmp_26_fu_761_p3);

assign and_ln301_fu_351_p2 = (xor_ln38_fu_281_p2 & c_V_fu_259_p2);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_01001 = ((ap_start == 1'b0) & (ap_start == 1'b1));
end

always @ (*) begin
    ap_block_pp0_stage0_11001 = ((ap_start == 1'b0) & (ap_start == 1'b1));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = ((ap_start == 1'b0) & (ap_start == 1'b1));
end

always @ (*) begin
    ap_block_state1_pp0_stage0_iter0 = (ap_start == 1'b0);
end

assign ap_block_state2_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start;

assign b_V_1_fu_791_p2 = (tmp_27_fu_769_p3 & and_ln301_9_fu_785_p2);

assign b_V_2_fu_1137_p2 = (tmp_42_fu_1115_p3 & and_ln301_15_fu_1131_p2);

assign b_V_3_fu_1483_p2 = (tmp_57_fu_1461_p3 & and_ln301_21_fu_1477_p2);

assign b_V_fu_451_p2 = (tmp_12_fu_429_p3 & and_ln301_3_fu_445_p2);

assign c_V_1_fu_599_p2 = (xor_ln85_fu_581_p2 & xor_ln85_2_fu_593_p2);

assign c_V_2_fu_945_p2 = (xor_ln133_fu_927_p2 & xor_ln133_2_fu_939_p2);

assign c_V_3_fu_1291_p2 = (xor_ln181_fu_1273_p2 & xor_ln181_2_fu_1285_p2);

assign c_V_fu_259_p2 = (xor_ln37_fu_241_p2 & xor_ln37_2_fu_253_p2);

assign hat_mul_out1_V_fu_363_p3 = ((and_ln301_1_fu_357_p2[0:0] === 1'b1) ? p_Result_2_fu_313_p4 : select_ln301_fu_343_p3);

assign hat_mul_out2_V_fu_703_p3 = ((and_ln301_7_fu_697_p2[0:0] === 1'b1) ? p_Result_5_fu_653_p4 : select_ln301_4_fu_683_p3);

assign hat_mul_out3_V_fu_1049_p3 = ((and_ln301_13_fu_1043_p2[0:0] === 1'b1) ? p_Result_14_fu_999_p4 : select_ln301_8_fu_1029_p3);

assign hat_mul_out4_V_fu_1395_p3 = ((and_ln301_19_fu_1389_p2[0:0] === 1'b1) ? p_Result_21_fu_1345_p4 : select_ln301_12_fu_1375_p3);

assign or_ln101_1_fu_749_p2 = (tmp_23_fu_719_p3 | or_ln101_fu_743_p2);

assign or_ln101_fu_743_p2 = (tmp_24_fu_727_p3 | tmp_22_fu_711_p3);

assign or_ln149_1_fu_1095_p2 = (tmp_38_fu_1065_p3 | or_ln149_fu_1089_p2);

assign or_ln149_fu_1089_p2 = (tmp_39_fu_1073_p3 | tmp_37_fu_1057_p3);

assign or_ln197_1_fu_1441_p2 = (tmp_53_fu_1411_p3 | or_ln197_fu_1435_p2);

assign or_ln197_fu_1435_p2 = (tmp_54_fu_1419_p3 | tmp_52_fu_1403_p3);

assign or_ln53_1_fu_409_p2 = (tmp_6_fu_379_p3 | or_ln53_fu_403_p2);

assign or_ln53_fu_403_p2 = (tmp_7_fu_387_p3 | tmp_5_fu_371_p3);

assign out_V = {{s10_V_fu_1709_p2[16:1]}};

assign p_Result_10_fu_209_p1 = grp_LFSR_fu_199_ap_return[15:0];

assign p_Result_11_fu_837_p4 = {{grp_LFSR_fu_199_ap_return[44:32]}};

assign p_Result_12_fu_863_p5 = {{{{tmp_30_fu_847_p3}, {p_Result_57_fu_855_p3}}, {p_Result_57_fu_855_p3}}, {p_Result_11_fu_837_p4}};

assign p_Result_13_fu_989_p4 = {{grp_LFSR_fu_199_ap_return[94:93]}};

assign p_Result_14_fu_999_p4 = {{{tmp_33_fu_911_p3}, {p_Result_13_fu_989_p4}}, {trunc_ln647_5_fu_985_p1}};

assign p_Result_15_fu_1009_p4 = {{grp_LFSR_fu_199_ap_return[92:91]}};

assign p_Result_16_fu_1019_p4 = {{{tmp_33_fu_911_p3}, {p_Result_15_fu_1009_p4}}, {trunc_ln647_5_fu_985_p1}};

assign p_Result_17_fu_1159_p4 = {{{tmp_44_fu_1151_p3}, {tmp_44_fu_1151_p3}}, {trunc_ln647_6_fu_1147_p1}};

assign p_Result_18_fu_1183_p4 = {{grp_LFSR_fu_199_ap_return[76:64]}};

assign p_Result_19_fu_1209_p5 = {{{{tmp_45_fu_1193_p3}, {p_Result_58_fu_1201_p3}}, {p_Result_58_fu_1201_p3}}, {p_Result_18_fu_1183_p4}};

assign p_Result_1_fu_303_p4 = {{grp_LFSR_fu_199_ap_return[30:29]}};

assign p_Result_20_fu_1335_p4 = {{grp_LFSR_fu_199_ap_return[126:125]}};

assign p_Result_21_fu_1345_p4 = {{{tmp_48_fu_1257_p3}, {p_Result_20_fu_1335_p4}}, {trunc_ln647_7_fu_1331_p1}};

assign p_Result_22_fu_1355_p4 = {{grp_LFSR_fu_199_ap_return[124:123]}};

assign p_Result_23_fu_1365_p4 = {{{tmp_48_fu_1257_p3}, {p_Result_22_fu_1355_p4}}, {trunc_ln647_7_fu_1331_p1}};

assign p_Result_24_fu_1505_p4 = {{{tmp_59_fu_1497_p3}, {tmp_59_fu_1497_p3}}, {trunc_ln647_8_fu_1493_p1}};

assign p_Result_25_fu_1529_p4 = {{grp_LFSR_fu_199_ap_return[108:96]}};

assign p_Result_26_fu_543_p4 = {{grp_LFSR_fu_199_ap_return[47:32]}};

assign p_Result_27_fu_1555_p5 = {{{{tmp_60_fu_1539_p3}, {p_Result_59_fu_1547_p3}}, {p_Result_59_fu_1547_p3}}, {p_Result_25_fu_1529_p4}};

assign p_Result_2_fu_313_p4 = {{{tmp_1_fu_225_p3}, {p_Result_1_fu_303_p4}}, {trunc_ln647_fu_299_p1}};

assign p_Result_32_fu_1657_p4 = {{s00_V_fu_1613_p2[16:1]}};

assign p_Result_33_fu_1683_p4 = {{s01_V_fu_1651_p2[16:1]}};

assign p_Result_3_fu_323_p4 = {{grp_LFSR_fu_199_ap_return[28:27]}};

assign p_Result_41_fu_889_p4 = {{grp_LFSR_fu_199_ap_return[79:64]}};

assign p_Result_49_fu_1235_p4 = {{grp_LFSR_fu_199_ap_return[111:96]}};

assign p_Result_4_fu_333_p4 = {{{tmp_1_fu_225_p3}, {p_Result_3_fu_323_p4}}, {trunc_ln647_fu_299_p1}};

assign p_Result_56_fu_509_p3 = grp_LFSR_fu_199_ap_return[32'd15];

assign p_Result_57_fu_855_p3 = grp_LFSR_fu_199_ap_return[32'd47];

assign p_Result_58_fu_1201_p3 = grp_LFSR_fu_199_ap_return[32'd79];

assign p_Result_59_fu_1547_p3 = grp_LFSR_fu_199_ap_return[32'd111];

assign p_Result_5_fu_653_p4 = {{{tmp_18_fu_565_p3}, {p_Result_s_6_fu_643_p4}}, {trunc_ln647_3_fu_639_p1}};

assign p_Result_60_fu_1581_p3 = hat_mul_out1_V_fu_363_p3[32'd15];

assign p_Result_61_fu_1589_p3 = {{p_Result_60_fu_1581_p3}, {hat_mul_out1_V_fu_363_p3}};

assign p_Result_62_fu_1597_p3 = hat_mul_out2_V_fu_703_p3[32'd15];

assign p_Result_63_fu_1605_p3 = {{p_Result_62_fu_1597_p3}, {hat_mul_out2_V_fu_703_p3}};

assign p_Result_64_fu_1619_p3 = hat_mul_out3_V_fu_1049_p3[32'd15];

assign p_Result_65_fu_1627_p3 = {{p_Result_64_fu_1619_p3}, {hat_mul_out3_V_fu_1049_p3}};

assign p_Result_66_fu_1635_p3 = hat_mul_out4_V_fu_1395_p3[32'd15];

assign p_Result_67_fu_1643_p3 = {{p_Result_66_fu_1635_p3}, {hat_mul_out4_V_fu_1395_p3}};

assign p_Result_68_fu_1667_p3 = s00_V_fu_1613_p2[32'd16];

assign p_Result_69_fu_1693_p3 = s01_V_fu_1651_p2[32'd16];

assign p_Result_6_fu_663_p4 = {{grp_LFSR_fu_199_ap_return[60:59]}};

assign p_Result_7_fu_673_p4 = {{{tmp_18_fu_565_p3}, {p_Result_6_fu_663_p4}}, {trunc_ln647_3_fu_639_p1}};

assign p_Result_8_fu_813_p4 = {{{tmp_29_fu_805_p3}, {tmp_29_fu_805_p3}}, {trunc_ln647_4_fu_801_p1}};

assign p_Result_9_fu_517_p5 = {{{{tmp_15_fu_501_p3}, {p_Result_56_fu_509_p3}}, {p_Result_56_fu_509_p3}}, {trunc_ln647_2_fu_497_p1}};

assign p_Result_s_6_fu_643_p4 = {{grp_LFSR_fu_199_ap_return[62:61]}};

assign p_Result_s_fu_473_p4 = {{{tmp_14_fu_465_p3}, {tmp_14_fu_465_p3}}, {trunc_ln647_1_fu_461_p1}};

assign s00_V_fu_1613_p2 = (p_Result_63_fu_1605_p3 + p_Result_61_fu_1589_p3);

assign s01_V_fu_1651_p2 = (p_Result_67_fu_1643_p3 + p_Result_65_fu_1627_p3);

assign s10_V_fu_1709_p2 = (tmp_9_fu_1701_p3 + tmp_8_fu_1675_p3);

assign select_ln301_10_fu_1169_p3 = ((b_V_2_fu_1137_p2[0:0] === 1'b1) ? z_V_4 : p_Result_17_fu_1159_p4);

assign select_ln301_11_fu_1221_p3 = ((a_V_2_fu_1101_p2[0:0] === 1'b1) ? p_Result_19_fu_1209_p5 : p_Result_41_fu_889_p4);

assign select_ln301_12_fu_1375_p3 = ((c_V_3_fu_1291_p2[0:0] === 1'b1) ? p_Result_23_fu_1365_p4 : z1_V_3);

assign select_ln301_14_fu_1515_p3 = ((b_V_3_fu_1483_p2[0:0] === 1'b1) ? z_V_3 : p_Result_24_fu_1505_p4);

assign select_ln301_15_fu_1567_p3 = ((a_V_3_fu_1447_p2[0:0] === 1'b1) ? p_Result_27_fu_1555_p5 : p_Result_49_fu_1235_p4);

assign select_ln301_2_fu_483_p3 = ((b_V_fu_451_p2[0:0] === 1'b1) ? z_V : p_Result_s_fu_473_p4);

assign select_ln301_3_fu_529_p3 = ((a_V_fu_415_p2[0:0] === 1'b1) ? p_Result_9_fu_517_p5 : p_Result_10_fu_209_p1);

assign select_ln301_4_fu_683_p3 = ((c_V_1_fu_599_p2[0:0] === 1'b1) ? p_Result_7_fu_673_p4 : z1_V_5);

assign select_ln301_6_fu_823_p3 = ((b_V_1_fu_791_p2[0:0] === 1'b1) ? z_V_5 : p_Result_8_fu_813_p4);

assign select_ln301_7_fu_875_p3 = ((a_V_1_fu_755_p2[0:0] === 1'b1) ? p_Result_12_fu_863_p5 : p_Result_26_fu_543_p4);

assign select_ln301_8_fu_1029_p3 = ((c_V_2_fu_945_p2[0:0] === 1'b1) ? p_Result_16_fu_1019_p4 : z1_V_4);

assign select_ln301_fu_343_p3 = ((c_V_fu_259_p2[0:0] === 1'b1) ? p_Result_4_fu_333_p4 : z1_V);

assign tmp_10_fu_395_p3 = grp_LFSR_fu_199_ap_return[32'd23];

assign tmp_11_fu_421_p3 = grp_LFSR_fu_199_ap_return[32'd26];

assign tmp_12_fu_429_p3 = grp_LFSR_fu_199_ap_return[32'd24];

assign tmp_13_fu_437_p3 = grp_LFSR_fu_199_ap_return[32'd25];

assign tmp_14_fu_465_p3 = z_V[32'd15];

assign tmp_15_fu_501_p3 = grp_LFSR_fu_199_ap_return[32'd15];

assign tmp_17_fu_557_p3 = z1_V_5[32'd14];

assign tmp_18_fu_565_p3 = z1_V_5[32'd15];

assign tmp_19_fu_573_p3 = z1_V_5[32'd13];

assign tmp_1_fu_225_p3 = z1_V[32'd15];

assign tmp_20_fu_605_p3 = grp_LFSR_fu_199_ap_return[32'd59];

assign tmp_21_fu_613_p3 = grp_LFSR_fu_199_ap_return[32'd60];

assign tmp_22_fu_711_p3 = grp_LFSR_fu_199_ap_return[32'd54];

assign tmp_23_fu_719_p3 = grp_LFSR_fu_199_ap_return[32'd52];

assign tmp_24_fu_727_p3 = grp_LFSR_fu_199_ap_return[32'd53];

assign tmp_25_fu_735_p3 = grp_LFSR_fu_199_ap_return[32'd55];

assign tmp_26_fu_761_p3 = grp_LFSR_fu_199_ap_return[32'd58];

assign tmp_27_fu_769_p3 = grp_LFSR_fu_199_ap_return[32'd56];

assign tmp_28_fu_777_p3 = grp_LFSR_fu_199_ap_return[32'd57];

assign tmp_29_fu_805_p3 = z_V_5[32'd15];

assign tmp_2_fu_233_p3 = z1_V[32'd13];

assign tmp_30_fu_847_p3 = grp_LFSR_fu_199_ap_return[32'd47];

assign tmp_32_fu_903_p3 = z1_V_4[32'd14];

assign tmp_33_fu_911_p3 = z1_V_4[32'd15];

assign tmp_34_fu_919_p3 = z1_V_4[32'd13];

assign tmp_35_fu_951_p3 = grp_LFSR_fu_199_ap_return[32'd91];

assign tmp_36_fu_959_p3 = grp_LFSR_fu_199_ap_return[32'd92];

assign tmp_37_fu_1057_p3 = grp_LFSR_fu_199_ap_return[32'd86];

assign tmp_38_fu_1065_p3 = grp_LFSR_fu_199_ap_return[32'd84];

assign tmp_39_fu_1073_p3 = grp_LFSR_fu_199_ap_return[32'd85];

assign tmp_3_fu_265_p3 = grp_LFSR_fu_199_ap_return[32'd27];

assign tmp_40_fu_1081_p3 = grp_LFSR_fu_199_ap_return[32'd87];

assign tmp_41_fu_1107_p3 = grp_LFSR_fu_199_ap_return[32'd90];

assign tmp_42_fu_1115_p3 = grp_LFSR_fu_199_ap_return[32'd88];

assign tmp_43_fu_1123_p3 = grp_LFSR_fu_199_ap_return[32'd89];

assign tmp_44_fu_1151_p3 = z_V_4[32'd15];

assign tmp_45_fu_1193_p3 = grp_LFSR_fu_199_ap_return[32'd79];

assign tmp_47_fu_1249_p3 = z1_V_3[32'd14];

assign tmp_48_fu_1257_p3 = z1_V_3[32'd15];

assign tmp_49_fu_1265_p3 = z1_V_3[32'd13];

assign tmp_4_fu_273_p3 = grp_LFSR_fu_199_ap_return[32'd28];

assign tmp_50_fu_1297_p3 = grp_LFSR_fu_199_ap_return[32'd123];

assign tmp_51_fu_1305_p3 = grp_LFSR_fu_199_ap_return[32'd124];

assign tmp_52_fu_1403_p3 = grp_LFSR_fu_199_ap_return[32'd118];

assign tmp_53_fu_1411_p3 = grp_LFSR_fu_199_ap_return[32'd116];

assign tmp_54_fu_1419_p3 = grp_LFSR_fu_199_ap_return[32'd117];

assign tmp_55_fu_1427_p3 = grp_LFSR_fu_199_ap_return[32'd119];

assign tmp_56_fu_1453_p3 = grp_LFSR_fu_199_ap_return[32'd122];

assign tmp_57_fu_1461_p3 = grp_LFSR_fu_199_ap_return[32'd120];

assign tmp_58_fu_1469_p3 = grp_LFSR_fu_199_ap_return[32'd121];

assign tmp_59_fu_1497_p3 = z_V_3[32'd15];

assign tmp_5_fu_371_p3 = grp_LFSR_fu_199_ap_return[32'd22];

assign tmp_60_fu_1539_p3 = grp_LFSR_fu_199_ap_return[32'd111];

assign tmp_6_fu_379_p3 = grp_LFSR_fu_199_ap_return[32'd20];

assign tmp_7_fu_387_p3 = grp_LFSR_fu_199_ap_return[32'd21];

assign tmp_8_fu_1675_p3 = {{p_Result_68_fu_1667_p3}, {p_Result_32_fu_1657_p4}};

assign tmp_9_fu_1701_p3 = {{p_Result_69_fu_1693_p3}, {p_Result_33_fu_1683_p4}};

assign tmp_fu_217_p3 = z1_V[32'd14];

assign trunc_ln647_1_fu_461_p1 = z_V[13:0];

assign trunc_ln647_2_fu_497_p1 = grp_LFSR_fu_199_ap_return[12:0];

assign trunc_ln647_3_fu_639_p1 = z1_V_5[12:0];

assign trunc_ln647_4_fu_801_p1 = z_V_5[13:0];

assign trunc_ln647_5_fu_985_p1 = z1_V_4[12:0];

assign trunc_ln647_6_fu_1147_p1 = z_V_4[13:0];

assign trunc_ln647_7_fu_1331_p1 = z1_V_3[12:0];

assign trunc_ln647_8_fu_1493_p1 = z_V_3[13:0];

assign trunc_ln647_fu_299_p1 = z1_V[12:0];

assign xor_ln133_1_fu_933_p2 = (tmp_34_fu_919_p3 ^ tmp_32_fu_903_p3);

assign xor_ln133_2_fu_939_p2 = (xor_ln133_1_fu_933_p2 ^ 1'd1);

assign xor_ln133_fu_927_p2 = (tmp_33_fu_911_p3 ^ tmp_32_fu_903_p3);

assign xor_ln134_1_fu_973_p2 = (tmp_36_fu_959_p3 ^ tmp_35_fu_951_p3);

assign xor_ln134_2_fu_979_p2 = (xor_ln134_1_fu_973_p2 ^ 1'd1);

assign xor_ln134_fu_967_p2 = (tmp_35_fu_951_p3 ^ tmp_33_fu_911_p3);

assign xor_ln181_1_fu_1279_p2 = (tmp_49_fu_1265_p3 ^ tmp_47_fu_1249_p3);

assign xor_ln181_2_fu_1285_p2 = (xor_ln181_1_fu_1279_p2 ^ 1'd1);

assign xor_ln181_fu_1273_p2 = (tmp_48_fu_1257_p3 ^ tmp_47_fu_1249_p3);

assign xor_ln182_1_fu_1319_p2 = (tmp_51_fu_1305_p3 ^ tmp_50_fu_1297_p3);

assign xor_ln182_2_fu_1325_p2 = (xor_ln182_1_fu_1319_p2 ^ 1'd1);

assign xor_ln182_fu_1313_p2 = (tmp_50_fu_1297_p3 ^ tmp_48_fu_1257_p3);

assign xor_ln37_1_fu_247_p2 = (tmp_fu_217_p3 ^ tmp_2_fu_233_p3);

assign xor_ln37_2_fu_253_p2 = (xor_ln37_1_fu_247_p2 ^ 1'd1);

assign xor_ln37_fu_241_p2 = (tmp_fu_217_p3 ^ tmp_1_fu_225_p3);

assign xor_ln38_1_fu_287_p2 = (tmp_4_fu_273_p3 ^ tmp_3_fu_265_p3);

assign xor_ln38_2_fu_293_p2 = (xor_ln38_1_fu_287_p2 ^ 1'd1);

assign xor_ln38_fu_281_p2 = (tmp_3_fu_265_p3 ^ tmp_1_fu_225_p3);

assign xor_ln85_1_fu_587_p2 = (tmp_19_fu_573_p3 ^ tmp_17_fu_557_p3);

assign xor_ln85_2_fu_593_p2 = (xor_ln85_1_fu_587_p2 ^ 1'd1);

assign xor_ln85_fu_581_p2 = (tmp_18_fu_565_p3 ^ tmp_17_fu_557_p3);

assign xor_ln86_1_fu_627_p2 = (tmp_21_fu_613_p3 ^ tmp_20_fu_605_p3);

assign xor_ln86_2_fu_633_p2 = (xor_ln86_1_fu_627_p2 ^ 1'd1);

assign xor_ln86_fu_621_p2 = (tmp_20_fu_605_p3 ^ tmp_18_fu_565_p3);

endmodule //multihat
